### ISSUE TITLE
![image](https://user-images.githubusercontent.com/20452814/183856594-c293091f-15a4-4912-a7bb-4f50b63fa1c5.png)

### ISSUE THREAD

**Issue by Adawntoremember** [glennawatson/ReactiveGit#122]
![image](https://user-images.githubusercontent.com/20452814/183856594-c293091f-15a4-4912-a7bb-4f50b63fa1c5.png)
you need to delete it from the file system add use `git add .` and `git commit -m "Remove app directory"` and `git push`

_Originally posted by @CodeDoctorDE in https://github.com/LinwoodDev/Butterfly/pull/245#issuecomment-1210353780_

**Comment by CodeDoctorDE** [comment]
Why tagging me?
I don't see a reason to post my comment of a pull request review here
